---

    name: Gitops project
    
    on:
      push:
        branches:
          - main
    
    jobs: 
      build_and_push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Set Short SHA
            run: |
              echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
          - name: Build Docker Image
            run: |
              docker build -t sammielas/gitopspro:${{ env.SHORT_SHA }} .
          - name: Login to Dockerhub
            run: |
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          - name: Push to Dockerhub
            run: |
              docker push sammielas/gitopspro:${{ env.SHORT_SHA }}
        # Configure Git identity for automated commits
          - name: Configure Git Author
            run: |
                git config --local user.email "samflicks@gmail.com"
                git config --local user.name "sammielas"
          # Update Helm chart configuration with new image version
          # Use sed to replace the existing image tag with new SHORT_SHA in values.yaml
             # This updates the Kubernetes deployment to use the newly built image
          - name: Update Helm Chart with new image tag
            env:
              PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
            run: |
                sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./gitops-pro-app/values.yaml
          - name: Push Updated Helm Chart
            env:
              PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
            run: |
                     git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/sammielas/gitops_pro.git
                     git add ./gitops-pro-app/values.yaml
                     git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
                     git push origin main
            